# Generated by Django 5.2.5 on 2025-09-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(help_text="Duration in minutes"),
        ),
    ]
