# Generated by Django 5.2.5 on 2025-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_alter_movie_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(help_text="Duration in minutes"),
        ),
    ]
