# Generated by Django 5.2.5 on 2025-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_movie_description_alter_movie_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.PositiveIntegerField(help_text="Duration in minutes"),
        ),
    ]
